#!/usr/bin/env python3
"""Stage the independent controller and reviewed dependency locks into a NEW directory.

Does not install dependencies, enable a host, migrate data, or sign/build an app.
"""
import argparse
import json
from pathlib import Path
import shutil
import sys
import tempfile
import zipfile


def stage(source, output):
    source = Path(source).resolve(strict=True)
    output = Path(output).absolute()
    # Import only the source packager, never the legacy server or a model runtime.
    sys.path.insert(0, str(source))
    from media_lab_core.studio_source_bundle import package_source
    if output.exists() or output.is_symlink():
        raise FileExistsError('Staging requires a new output directory')
    with tempfile.TemporaryDirectory(prefix='.controller-stage-', dir=output.parent) as temporary:
        archive = Path(temporary) / 'controller.zip'
        receipt = package_source(source, archive, include_runtime_locks=True)
        # The archive is generated by the fixed, hash-checked source allowlist.
        unpacked = Path(temporary) / 'source'
        with zipfile.ZipFile(archive) as bundle:
            bundle.extractall(unpacked)
        output.mkdir()  # Exclusive: never replace an existing staged tree.
        try:
            for child in unpacked.iterdir():
                shutil.move(str(child), output / child.name)
        except BaseException:
            shutil.rmtree(output)
            raise
    return {**receipt, 'runtime': 'independent-studio',
            'scope': 'Source and dependency locks only; dependencies, models and host activation are not included.'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=Path(__file__).resolve().parents[2] / 'media-lab')
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(stage(args.source, args.output), sort_keys=True))


if __name__ == '__main__':
    main()
